name: Build

on:
  push:
    branches:
      - dev
      - master
      - release-*
      - 1.*
  pull_request:
    branches:
      - dev
      - master
      - release-*
      - 1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, uid-runner]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and tests
        run: ./mvnw -B clean verify -Pe2e,integration-test

      - name: Send message to Slack channel
        uses: act10ns/slack@v1
        if: ${{ failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master') }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
